<!DOCTYPE html>
<html>
<head>
	<meta charset=utf-8>
	<meta name=viewport content="width=device-width,initial-scale=1">
	<title>БЛАГОБУД - ВИРОБНИЧА КОМПАНІЯ</title>
	<link rel="stylesheet" href="/fonts/fontawesome/css/all.css">
	<link rel="shortcut icon" href="/img/favicon.png" type="image/png" />
</head>
<body>
<div id=app></div>
<script>
	let someoneelse = "<?=$this->secure?>";
</script>
<script type=text/javascript src=/main.js></script>
</body>
</html>